### ISSUE TITLE
[FEAT] Option to turn off slow connection detection / detect links inside *ngIf (force)

### ISSUE THREAD

**Issue by silveoj** [mgechev/ngx-quicklink#49]
1. Is there possibility to add option to turn off this feature?

   > Checks if the user isn't on a slow connection ... or has data-saver enabled

   for example: 
   ```
   QuicklinkModule.forRoot({
    slowConnection: false, // or something similar, more general.
   })
   ```

   In Chrome Dev tools: Network Tab - preloading works for Fast 3G. But it doesn't work for Slow 3G.

2. We hide some routerLinks in `*ngIf`. Is there possibility to add option like `preload: true` or something else to always preload modules? I know our package has this option (`preload: false`). As variant I use own CustomPreloadingStrategy. Or better way is to extend our QuicklinkStrategy?

Thanks.

**Comment by mgechev** [comment]
Not sure if we should enable this under a flag if it's not considered a best practice. Let's think about it for a bit and make a decision after that.

**Comment by silveoj** [comment]
### Initial data:
For example I have `MyModule` module.
`MyModule` contains only one `MyMenu` component with this menu:
- Item 1 (`item-1` route)
- Item 2 (`item-2` route)
- Item 3 (`item-3` route)

Each link in menu is own module = 3 submodules.
I don't need any data from server for this menu (except lazy loading modules).

### Scenario:
I open `MyMenu` page with Network tab and wait for 60 seconds:
- Fast 3G already preloaded 3 submodules.
- Slow 3G even doesn't preload modules (by design). But I spent 60 seconds and can preload it. So if I click on `Item-1` link I will have delay to load `Item1Module`  js.
(click `Item-1` --> but nothing --> need to wait for 1-3 seconds (while loading modules) -> now I see spinner)

**Comment by razmjo-netlinks** [comment]
I had installed this package on my project. This package increased the CPU usage to 100%. because I have a lot of lazy loaded routes and each lazy loaded routes has it own lazy loaded routes. From my point of view, it load all nested routes. which takes time, slow the performance and increase the CPU usage.

After removing this package. my website become faster and the CPU usage does not increased.

I am not sure if my point of view is correct or not. after removing this package, everything works perfectly.

**Comment by nimatullah** [comment]
I had installed this package on my project. This package increased the CPU usage to 100%. because I have a lot of lazy loaded routes and each lazy loaded route has its own lazy loaded routes. From my point of view, it loads all nested routes. which takes time, slow the performance, and increase the CPU usage.

After removing this package. my website becomes faster and the CPU usage does not increase.

I am not sure if my point of view is correct or not. after removing this package, everything works perfectly.

**Comment by mgechev** [comment]
@nimatullah yes, looks like [this](https://github.com/mgechev/ngx-quicklink/issues/63) is the reason for that. Follow https://github.com/mgechev/ngx-quicklink/issues/63 for updates to see when you can enable ngx-quicklink back.

**Comment by mgechev** [comment]
Let's keep this outside the scope of the project.
