### ISSUE TITLE
How to use with Ionic tabs?

### ISSUE THREAD

**Issue by muuvmuuv** [mgechev/ngx-quicklink#68]
I would love to use this lib with ionic to preload our app routes but it seems that it is not working with the ionic tab component which is using router links internally.

```html
<ion-tabs>
  <ion-tab-bar>
    <ion-tab-button tab="explore">
      <app-icon name="planet"></app-icon>
    </ion-tab-button>
  </ion-tab-bar>
</ion-tabs>
```

> https://ionicframework.com/docs/api/tabs

**Comment by mgechev** [comment]
We can potentially expand the selector to include `ion-tab-button`, but we'd also need to ensure they use the Angular router. @mhartington would be able to share some insights here.

**Comment by mhartington** [comment]
Internally, we use angular router to handle navigation, but we don't set routerLinks or hrefs on the component itself. I think the use case can make sense, but not sure if it makes sense to preload different tabs itself. 

@muuvmuuv If you're using this with the current setup, you should be able to preload the different routes for a single tab without issues.

**Comment by muuvmuuv** [comment]
@mhartington Preload tabs make a lot of sense; imagine you just installed the app and the tabs are heavy components with lots of logic. If the tabs page has not been opened yet it takes long enough to make the user think his device is slow. Preloading tabs on idle is a big user experience leap. Especially because tabs are navigation and a user expect to navigate without waiting too long.

Having `routerLink` inside a tab works fine and increased the page response in our app by a significant amount.

**Comment by mhartington** [comment]
>and the tabs are heavy components with lots of logic 
Preloading won't solve this problem. Preloading/prefetching downloads the resource, yes, but it does not execute the code in question. So if you component is very complex and fully of computational work, prefetching does not make it faster. Other approaches are to utilize [Ionic's lifecycle events](https://ionicframework.com/docs/angular/lifecycle) to defer tasks until the component has finished animating in.


If the idea is to preload the first component of each tab, then the defaults provided by the ionic starter templates should be enough to loading the components from the tabs.

https://github.com/ionic-team/starters/blob/master/angular/official/tabs/src/app/app-routing.module.ts

Either way, this only downloads the resource (for network latency), but does not execute. So if we take the situation that the app is on someones device, the network times will be basically 0 (since all files are local to the device). Meaning that prefetching won't really have an effect here. 


@mgechev there's some logic in place to wire up the `tab` property on the `ion-tab-button`, which could be used here. Happy to help out and send a PR if you'd like.

**Comment by muuvmuuv** [comment]
Ohh, sorry, I thought with loaded it means that it will partially be executed. So just not rendered.

**Comment by mgechev** [comment]
Let's keep the issue open for a bit to collect more feedback. I'm leaning towards keeping Ionic support outside of the scope of the project. Any new feature adds up to the production bundle.
